package com.google.android.gms.p035d;

import com.google.android.gms.common.api.C0590f;
import com.google.android.gms.common.api.C0593h;
import com.google.android.gms.common.api.C0594i;
import com.google.android.gms.common.api.Status;

/* renamed from: com.google.android.gms.d.es */
public final class C0832es<R extends C0593h> extends C0590f<R> {

    /* renamed from: a */
    private final Status f1883a;

    /* access modifiers changed from: 0000 */
    /* renamed from: a */
    public final Status mo2156a() {
        return this.f1883a;
    }

    /* renamed from: a */
    public final void mo1593a(C0594i<? super R> iVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
